call plug#begin("~/.vim/plugged")
  " Theme
  " Plug 'dracula/vim'

  " Language Client
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  let g:coc_global_extensions = ['coc-emmet', 'coc-css', 'coc-html', 'coc-json', 'coc-prettier', 'coc-rust-analyzer', 'coc-sh']
  " TypeScript Highlighting
  Plug 'dyng/ctrlsf.vim' " search across all folders
  Plug 'leafgarland/typescript-vim'
  Plug 'peitalin/vim-jsx-typescript'
  Plug 'dhruvasagar/vim-zoom'

  " File Explorer with Icons
  Plug 'scrooloose/nerdtree'
  Plug 'ryanoasis/vim-devicons'

  " File Search
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
  Plug 'junegunn/fzf.vim'
  " add / remove comments
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-surround'

  " rust stuff from https://blog.logrocket.com/configuring-vim-rust-development/. His config is https://github.com/zupzup/dotfiles-linux/blob/main/.vimrc
  " Note that you have to run :CocInstall coc-rust-analyzer after PlugInstall
  Plug 'rust-lang/rust.vim'
  Plug 'timonv/vim-cargo'
  " coc - C-space to suggest, C-y to accept
  " Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'dense-analysis/ale'

  
call plug#end()
let g:rustfmt_autosave = 1
let g:rustfmt_emit_files = 1
let g:rustfmt_fail_silently = 0
" This might need to change https://stackoverflow.com/a/72341811/494635
" https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim
" You need to have node installed. You can specify it below... or, on OSX use
" nvm alias default 10.17.0
" let g:coc_node_path = '/home/damien/.nvm/versions/node/v16.14.2/bin/node'
" inoremap <silent><expr> <TAB>
"       \ pumvisible() ? "\<C-n>" :
"       \ <SID>check_back_space() ? "\<TAB>" :
"       \ coc#refresh()
" inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

" See https://github.com/neoclide/coc.nvim/pull/3862
" Checkout :h coc-completion for details.
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
  inoremap <silent><expr> <C-x><C-z> coc#pum#visible() ? coc#pum#stop() : "\<C-x>\<C-z>"
  " remap for complete to use tab and <cr>
  inoremap <silent><expr> <TAB>
        \ coc#pum#visible() ? coc#pum#next(1):
        \ <SID>check_back_space() ? "\<Tab>" :
        \ coc#refresh()
  inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
  inoremap <silent><expr> <c-space> coc#refresh()

  hi CocSearch ctermfg=12 guifg=#18A3FF
  hi CocMenuSel ctermbg=109 guibg=#13354A
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
" Enable theming support
if (has("termguicolors"))
 set termguicolors
endif

" https://learnvimscriptthehardway.stevelosh.com/chapters/06.html
let mapleader = "-"

" Theme
" syntax enable
" colorscheme dracula
  colorscheme evening
  " Language Client
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  let g:coc_global_extensions = ['coc-emmet', 'coc-css', 'coc-html', 'coc-json', 'coc-prettier', 'coc-tsserver', 'coc-rust-analyzer']
  " TypeScript Highlighting
  Plug 'leafgarland/typescript-vim'
  Plug 'peitalin/vim-jsx-typescript'
  Plug 'dhruvasagar/vim-zoom'

  " File Explorer with Icons
  Plug 'scrooloose/nerdtree'
  Plug 'ryanoasis/vim-devicons'

  " File Search
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
  Plug 'junegunn/fzf.vim'
  " add / remove comments
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-surround'

  " rust stuff from https://blog.logrocket.com/configuring-vim-rust-development/. His config is https://github.com/zupzup/dotfiles-linux/blob/main/.vimrc
  " Note that you have to run :CocInstall coc-rust-analyzer after PlugInstall
  Plug 'rust-lang/rust.vim'
  Plug 'timonv/vim-cargo'
  " coc - C-space to suggest, C-y to accept
  " Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'dense-analysis/ale'

  
call plug#end()
let g:rustfmt_autosave = 1
let g:rustfmt_emit_files = 1
let g:rustfmt_fail_silently = 0
" This might need to change https://stackoverflow.com/a/72341811/494635
" https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim
" You need to have node installed. You can specify it below... or, on OSX use
" nvm alias default 10.17.0
let g:coc_node_path = trim(system('which node'))
" let g:coc_node_path = '/home/damien/.nvm/versions/node/v16.14.2/bin/node'
" inoremap <silent><expr> <TAB>
"       \ pumvisible() ? "\<C-n>" :
"       \ <SID>check_back_space() ? "\<TAB>" :
"       \ coc#refresh()
" inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

" See https://github.com/neoclide/coc.nvim/pull/3862
" Checkout :h coc-completion for details.
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
  inoremap <silent><expr> <C-x><C-z> coc#pum#visible() ? coc#pum#stop() : "\<C-x>\<C-z>"
  " remap for complete to use tab and <cr>
  inoremap <silent><expr> <TAB>
        \ coc#pum#visible() ? coc#pum#next(1):
        \ <SID>check_back_space() ? "\<Tab>" :
        \ coc#refresh()
  inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
  inoremap <silent><expr> <c-space> coc#refresh()

  hi CocSearch ctermfg=12 guifg=#18A3FF
  hi CocMenuSel ctermbg=109 guibg=#13354A
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
" Enable theming support

let g:NERDTreeShowHidden = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeIgnore = []
let g:NERDTreeStatusline = ''
" Automaticaly close nvim if NERDTree is only thing left open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" Toggle
nnoremap <silent> <C-b> :NERDTreeToggle<CR>

nnoremap <C-p> :FZF<CR>
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-s': 'split',
  \ 'ctrl-v': 'vsplit'
  \}
" requires silversearcher-ag
" used to ignore gitignore files
let $FZF_DEFAULT_COMMAND = 'ag --hidden -g ""'

" open new split panes to right and below
set splitright
set splitbelow
set number relativenumber
" turn terminal to normal mode with escape
tnoremap <Esc> <C-\><C-n>

" work around escape key j and k will exit insert mode. 
inoremap kj <Esc> ^`
" lets you quickly open init.vim for editing!
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" use alt+hjkl to move between split/vsplit panels
tnoremap <A-h> <C-\><C-n><C-w>h
tnoremap <A-j> <C-\><C-n><C-w>j
tnoremap <A-k> <C-\><C-n><C-w>k
tnoremap <A-l> <C-\><C-n><C-w>l
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l
" Unmap the arrow keys to force hjkl (https://vi.stackexchange.com/a/5854)
" noremap <Up> <Nop>
" noremap <Down> <Nop>
" noremap <Left> <Nop>
" noremap <Right> <Nop>
" start terminal in insert mode
au BufEnter * if &buftype == 'terminal' | :startinsert | endif

" open terminal on ctrl+;
" uses zsh instead of bash
function! OpenTerminal()
  split term://bash
  resize 10
endfunction
nnoremap <c-n> :call OpenTerminal()<CR>


" switch marks to make lowercase global https://unix.stackexchange.com/questions/154845/reverse-global-and-local-marks-in-vi-vim
nnoremap ma mA
nnoremap mb mB
nnoremap mc mC
nnoremap md mD
nnoremap me mE
nnoremap mf mF
nnoremap mg mG
nnoremap mh mH
nnoremap `a `A
nnoremap 'a 'A
nnoremap `b `B
nnoremap 'b 'B
nnoremap `c `C
nnoremap 'c 'C
nnoremap `d `D
nnoremap 'd 'D
nnoremap `e `E
nnoremap 'e 'E
nnoremap `f `F
nnoremap 'f 'F
nnoremap `g `G
nnoremap 'g 'G
nnoremap `h `H
nnoremap 'h 'H


